# Generated by Django 4.2.6 on 2024-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0002_inputdata_transcript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputdata",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "Anh"),
                    ("ko", "Hàn Quốc"),
                    ("vi", "Việt"),
                    ("es", "Tây Ban Nha"),
                    ("fr", "Pháp"),
                    ("de", "Đức"),
                    ("ja", "Nhật"),
                    ("zh", "Trung Quốc"),
                    ("ru", "Nga"),
                    ("pt-BR", "Bồ Đào Nha (Brazil)"),
                    ("pt-PT", "Bồ Đào Nha (Bồ Đào Nha)"),
                ],
                default="en",
                max_length=20,
            ),
        ),
    ]
